server:
  port: 8080
  error:
    include-binding-errors: always
    include-message: always
    path: /user/error
    whitelabel:
      enabled: false

spring:
  application:
    name: document
  jackson:
    default-property-inclusion: non_null
    serialization:
      fail-on-empty-beans: false
      close-closeable: true
      flush-after-write-value: true
      write-date-keys-as-timestamps: false
    deserialization:
      fail-on-unknown-properties: false
  datasource:
    url: jdbc:postgresql://localhost:5432/document
    username: michael
    password: password
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: update
      show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
        globally_quoted_identifiers: true
    open-in-view: false
  mail:
    host: localhost
    port: 1025
    username: hello
    password: hello
    properties:
      mail:
        smtp:
          ssl:
            trust: "*"
          auth: true
          starttls:
            enable: true
          connectiontimeout: 5000
          timeout: 3000
          writetimeout: 5000
  sql:
    init:
      mode: never
      continue-on-error: false
      schema-locations: classpath:/data/schema.sql
      data-locations: classpath:data/data.sql
  servlet:
    multipart:
      enabled: true
      max-file-size: 1000MB
      max-request-size: 1000MB

jwt:
  expiration: 7000000
  secret: secretsecretsecretsecretsecretsecretsecretsecretsecretsecretsecretsecretsecretsecretsecretsecret